engines:
  markdownlint:
    enabled: true
    checks:
      MD024:
        enabled: false
      MD009:
        enabled: false
      MD013:
        enabled: false

plugins: 
  git-legal:
    enabled: true
  sonar-python:
    enabled: true