version: 2
plugins: 
  git-legal:
    enabled: true
  sonar-python:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD024:
        enabled: false
      MD009:
        enabled: false
      MD013:
        enabled: false
  pep8:
    enabled: true
  fixme:
    enabled: true
  bandit:
    enabled: true