version = 1

test_patterns = [
  "MetaStalk/**",
]
exclude_patterns = [
  "tests/*"
]
[[transformers]]
name = "black"
enabled = true

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"

[analyzers.meta]
runtime_version = "3.x.x"
max_line_length = 100
  
[[analyzers]]
name = "test-coverage"
enabled = true