version = 1

test_patterns = [
  "Pystalk.py",
  "modules/**",
  "utils/**"
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"

  
[[analyzers]]
name = "test-coverage"
enabled = true