stages:
- Code_Checking
- test

include:
  - template: SAST.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml


.test:
  coverage: '/TOTAL\s*\d*\s*\d*\s*(\d*)%/'
  artifacts:
    paths:
    - PyStalk.log
  before_script:
    - pip install -U pip
  script:
    - pip install -r requirements.txt --quiet
    - pip install pylint flake8 coverage bandit --quiet
    - pylint --ignored-classes=_socketobject PyStalk.py ./utils/ ./modules/
    - flake8 PyStalk.py ./utils/ ./modules/ --statistics --show-source
    - coverage run --source . ./PyStalk.py ./utils/ExamplePhotos/ -t -d
  after_script:
    - coverage report

python-3.5:
  extends: ".test"
  stage: Code_Checking
  image: python:3.5

python-3.6:
  extends: ".test"
  stage: Code_Checking
  image: python:3.6

python-3.7:
  extends: ".test"
  stage: Code_Checking
  image: python:3.7

python-3.8:
  extends: ".test"
  stage: Code_Checking
  image: python:3.8
