stages:
- test

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

.test:
  script:
    - pip install -r requirements.txt
    - pip install pylint --quiet
    - pylint --ignored-classes=_socketobject PyStalk.py

python-3.4:
  extends: ".test"
  stage: test
  image: python:3.4

python-3.5:
  extends: ".test"
  stage: test
  image: python:3.5

python-3.6:
  extends: ".test"
  stage: test
  image: python:3.6

python-3.7:
  extends: ".test"
  stage: test
  image: python:3.7

python-3.8:
  extends: ".test"
  stage: test
  image: python:3.8
