stages:
- test
- Code_Checking

include:
  - template: SAST.gitlab-ci.yml


.check:
  coverage: '/TOTAL\s*\d*\s*\d*\s*(\d*)%/'
  artifacts:
    paths:
    - PyStalk.log
    - htmlcov/*
    - bandit.json
  before_script:
    - pip install -U pip
  script:
    - pip install -r requirements.txt --quiet
    - pip install pylint flake8 coverage bandit --quiet
    - pylint --ignored-classes=_socketobject PyStalk.py ./utils/ ./modules/
    - flake8 PyStalk.py ./utils/ ./modules/ --statistics --show-source
    - bandit -r -f json PyStalk.py ./utils/ ./modules/ > bandit.json
    - coverage run --source . ./PyStalk.py ./utils/ExamplePhotos/ -t -d
  after_script:
    - coverage report
    - coverage html

python-3.5:
  extends: ".check"
  stage: Code_Checking
  image: python:3.5

python-3.6:
  extends: ".check"
  stage: Code_Checking
  image: python:3.6

python-3.7:
  extends: ".check"
  stage: Code_Checking
  image: python:3.7

python-3.8:
  extends: ".check"
  stage: Code_Checking
  image: python:3.8
