stages:
- Code_Checking
- test
- Test_Build

include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml


license_scanning:
  only:
    refs:
      - tags
      - master

Coverage:
  image: python:3.7
  stage: test
  coverage: '/TOTAL\s*\d*\s*\d*\s*(\d*)%/'
  artifacts:
    paths:
    - MetaStalk.log
    - htmlcov/*
    - bandit.json
  before_script:
    - pip install -U pip coverage -r requirements.txt --quiet
    - curl https://deepsource.io/cli | sh
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; chmod +x ./cc-test-reporter; ./cc-test-reporter before-build
  script:
    - coverage run -a --source . ./MetaStalk/main.py ./ExamplePhotos/ -t -d
    - coverage run -a --source . ./MetaStalk/main.py ./ExamplePhotos/Panasonic_DMC-FZ30.jpg ./ExamplePhotos/DSCN0010.jpg -t -d
  after_script:
    - coverage report
    - coverage html
    - coverage xml
    - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
    - ./cc-test-reporter after-build
    - bash <(curl -s https://codecov.io/bash)

.check:
  stage: Code_Checking
  before_script:
    - pip install -U pip -r requirements.txt -r requirements-dev.txt --quiet
  script:
    - pylint --rcfile=tox.ini ./MetaStalk
    - flake8 ./MetaStalk --statistics --show-source
    - time python3 ./MetaStalk/main.py ./ExamplePhotos/ -d -t

python-3.6:
  extends: ".check"
  image: python:3.6

python-3.7:
  extends: ".check"
  image: python:3.7

python-3.8:
  extends: ".check"
  image: python:3.8


.build:
  stage: test
  before_script:
    - pip install -U setuptools twine --quiet
  script:
    - python setup.py sdist bdist_wheel
    - python -m twine check dist/*
  except:
    - tags

python-3.6-build:
  extends: ".build"
  image: python:3.6
  artifacts:
    paths:
    - dist/

python-3.7-build:
  extends: ".build"
  image: python:3.7
  artifacts:
    paths:
    - dist/

python-3.8-build:
  extends: ".build"
  image: python:3.8
  artifacts:
    paths:
    - dist/

.test:
  stage: Test_Build
  before_script:
    - pip install -U pip --quiet
  script:
    - pip install dist/*.whl
    - pip show -f metastalk
    - command -v metastalk
    - metastalk ./ExamplePhotos/ -t -d
    - metastalk ./ExamplePhotos/Panasonic_DMC-FZ30.jpg ./ExamplePhotos/DSCN0010.jpg -t -d
  except:
    - tags

python-3.6-test:
  extends: ".test"
  image: python:3.6

python-3.7-test:
  extends: ".test"
  image: python:3.7

python-3.8-test:
  extends: ".test"
  image: python:3.8
    