stages:
- Code_Checking
- test

include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

variables:
  DS_DISABLE_DIND: "true"

gemnasium-python-dependency_scanning:
  stage: test
  before_script:
  - pip install numpy
  only:
    refs:
      - master
      - schedules


Coverage:
  image: python:3.7
  stage: test
  coverage: '/TOTAL\s*\d*\s*\d*\s*(\d*)%/'
  artifacts:
    paths:
    - PyStalk.log
    - htmlcov/*
    - bandit.json
  before_script:
    - pip install -U pip
    - curl https://deepsource.io/cli | sh
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
  script:
    - pip install -r requirements.txt --quiet
    - pip install coverage --quiet
    - coverage run -a --source . ./PyStalk.py ./utils/ExamplePhotos/ -t -d
    - coverage run -a --source . ./PyStalk.py ./utils/ExamplePhotos/Panasonic_DMC-FZ30.jpg ./utils/ExamplePhotos/DSCN0010.jpg -t -d
  after_script:
    - coverage report
    - coverage html
    - coverage xml
    - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
    - ./cc-test-reporter after-build
    - bash <(curl -s https://codecov.io/bash)

.check:
  stage: Code_Checking
  before_script:
    - pip install -U pip
  script:
  - pip install -r requirements.txt bandit pylint flake8 --quiet
#  - pip install -r requirements-dev.txt --quiet
  - pylint --ignored-classes=_socketobject PyStalk.py ./utils/ ./modules/
  - flake8 PyStalk.py ./utils/ ./modules/ --statistics --show-source
  - bandit -r -f json PyStalk.py ./utils/ ./modules/ > bandit.json
  - time python3 ./PyStalk.py ./utils/ExamplePhotos/ -d -t
  artifacts:
    paths:
    - bandit.json


python-3.5:
  extends: ".check"
  image: python:3.5

python-3.6:
  extends: ".check"
  image: python:3.6

python-3.7:
  extends: ".check"
  image: python:3.7

python-3.8:
  extends: ".check"
  image: python:3.8