[LOGGING]

# Format style used to check logging format string. `old` means using %
# formatting, while `new` is for `{}` formatting.
logging-format-style=new

[MESSAGES CONTROL]
disable=invalid-name, logging-too-many-args, wrong-import-position

[flake8]
ignore=E402